'use strict'

import '@fancyapps/fancybox'
import 'slick-carousel/slick/slick.min'

import './faq'
import './viewport'
import './menuPopup'
import './statistics'
import './indexTutorials'
import './indexGrow'
import './indexPlans'
import './indexWe'
import './indexPopup'
import './indexCurrency'
import './indexTerms'